// Color Palette
export const palette = {
  blue100: "var(--seed-color-palette-blue-100)",
  blue200: "var(--seed-color-palette-blue-200)",
  blue300: "var(--seed-color-palette-blue-300)",
  blue400: "var(--seed-color-palette-blue-400)",
  blue500: "var(--seed-color-palette-blue-500)",
  blue600: "var(--seed-color-palette-blue-600)",
  blue700: "var(--seed-color-palette-blue-700)",
  blue800: "var(--seed-color-palette-blue-800)",
  blue900: "var(--seed-color-palette-blue-900)",
  blue1000: "var(--seed-color-palette-blue-1000)",

  carrot100: "var(--seed-color-palette-carrot-100)",
  carrot200: "var(--seed-color-palette-carrot-200)",
  carrot300: "var(--seed-color-palette-carrot-300)",
  carrot400: "var(--seed-color-palette-carrot-400)",
  carrot500: "var(--seed-color-palette-carrot-500)",
  carrot600: "var(--seed-color-palette-carrot-600)",
  carrot700: "var(--seed-color-palette-carrot-700)",
  carrot800: "var(--seed-color-palette-carrot-800)",
  carrot900: "var(--seed-color-palette-carrot-900)",
  carrot1000: "var(--seed-color-palette-carrot-1000)",

  gray00: "var(--seed-color-palette-gray-00)",
  gray100: "var(--seed-color-palette-gray-100)",
  gray200: "var(--seed-color-palette-gray-200)",
  gray300: "var(--seed-color-palette-gray-300)",
  gray400: "var(--seed-color-palette-gray-400)",
  gray500: "var(--seed-color-palette-gray-500)",
  gray600: "var(--seed-color-palette-gray-600)",
  gray700: "var(--seed-color-palette-gray-700)",
  gray800: "var(--seed-color-palette-gray-800)",
  gray900: "var(--seed-color-palette-gray-900)",
  gray1000: "var(--seed-color-palette-gray-1000)",

  green100: "var(--seed-color-palette-green-100)",
  green200: "var(--seed-color-palette-green-200)",
  green300: "var(--seed-color-palette-green-300)",
  green400: "var(--seed-color-palette-green-400)",
  green500: "var(--seed-color-palette-green-500)",
  green600: "var(--seed-color-palette-green-600)",
  green700: "var(--seed-color-palette-green-700)",
  green800: "var(--seed-color-palette-green-800)",
  green900: "var(--seed-color-palette-green-900)",
  green1000: "var(--seed-color-palette-green-1000)",

  purple100: "var(--seed-color-palette-purple-100)",
  purple200: "var(--seed-color-palette-purple-200)",
  purple300: "var(--seed-color-palette-purple-300)",
  purple400: "var(--seed-color-palette-purple-400)",
  purple500: "var(--seed-color-palette-purple-500)",
  purple600: "var(--seed-color-palette-purple-600)",
  purple700: "var(--seed-color-palette-purple-700)",
  purple800: "var(--seed-color-palette-purple-800)",
  purple900: "var(--seed-color-palette-purple-900)",
  purple1000: "var(--seed-color-palette-purple-1000)",

  red100: "var(--seed-color-palette-red-100)",
  red200: "var(--seed-color-palette-red-200)",
  red300: "var(--seed-color-palette-red-300)",
  red400: "var(--seed-color-palette-red-400)",
  red500: "var(--seed-color-palette-red-500)",
  red600: "var(--seed-color-palette-red-600)",
  red700: "var(--seed-color-palette-red-700)",
  red800: "var(--seed-color-palette-red-800)",
  red900: "var(--seed-color-palette-red-900)",
  red1000: "var(--seed-color-palette-red-1000)",

  staticBlack: "var(--seed-color-palette-static-black)",
  staticWhite: "var(--seed-color-palette-static-white)",
  staticBlackAlpha100: "var(--seed-color-palette-static-black-alpha-100)",
  staticBlackAlpha200: "var(--seed-color-palette-static-black-alpha-200)",
  staticBlackAlpha300: "var(--seed-color-palette-static-black-alpha-300)",
  staticBlackAlpha400: "var(--seed-color-palette-static-black-alpha-400)",
  staticBlackAlpha500: "var(--seed-color-palette-static-black-alpha-500)",
  staticBlackAlpha600: "var(--seed-color-palette-static-black-alpha-600)",
  staticBlackAlpha700: "var(--seed-color-palette-static-black-alpha-700)",
  staticBlackAlpha800: "var(--seed-color-palette-static-black-alpha-800)",
  staticBlackAlpha900: "var(--seed-color-palette-static-black-alpha-900)",
  staticBlackAlpha1000: "var(--seed-color-palette-static-black-alpha-1000)",
  staticWhiteAlpha50: "var(--seed-color-palette-static-white-alpha-50)",
  staticWhiteAlpha100: "var(--seed-color-palette-static-white-alpha-100)",
  staticWhiteAlpha200: "var(--seed-color-palette-static-white-alpha-200)",
  staticWhiteAlpha300: "var(--seed-color-palette-static-white-alpha-300)",
  staticWhiteAlpha400: "var(--seed-color-palette-static-white-alpha-400)",
  staticWhiteAlpha500: "var(--seed-color-palette-static-white-alpha-500)",
  staticWhiteAlpha600: "var(--seed-color-palette-static-white-alpha-600)",
  staticWhiteAlpha700: "var(--seed-color-palette-static-white-alpha-700)",
  staticWhiteAlpha800: "var(--seed-color-palette-static-white-alpha-800)",
  staticWhiteAlpha900: "var(--seed-color-palette-static-white-alpha-900)",
  staticWhiteAlpha1000: "var(--seed-color-palette-static-white-alpha-1000)",

  yellow100: "var(--seed-color-palette-yellow-100)",
  yellow200: "var(--seed-color-palette-yellow-200)",
  yellow300: "var(--seed-color-palette-yellow-300)",
  yellow400: "var(--seed-color-palette-yellow-400)",
  yellow500: "var(--seed-color-palette-yellow-500)",
  yellow600: "var(--seed-color-palette-yellow-600)",
  yellow700: "var(--seed-color-palette-yellow-700)",
  yellow800: "var(--seed-color-palette-yellow-800)",
  yellow900: "var(--seed-color-palette-yellow-900)",
  yellow1000: "var(--seed-color-palette-yellow-1000)",
};

// Foreground Colors
export const fg = {
  neutral: "var(--seed-color-fg-neutral)",
  placeholder: "var(--seed-color-fg-placeholder)",
  disabled: "var(--seed-color-fg-disabled)",
  brand: "var(--seed-color-fg-brand)",
  informative: "var(--seed-color-fg-informative)",
  critical: "var(--seed-color-fg-critical)",
  positive: "var(--seed-color-fg-positive)",
  warning: "var(--seed-color-fg-warning)",
  brandContrast: "var(--seed-color-fg-brand-contrast)",
  criticalContrast: "var(--seed-color-fg-critical-contrast)",
  informativeContrast: "var(--seed-color-fg-informative-contrast)",
  neutralMuted: "var(--seed-color-fg-neutral-muted)",
  neutralSubtle: "var(--seed-color-fg-neutral-subtle)",
  neutralInverted: "var(--seed-color-fg-neutral-inverted)",
  positiveContrast: "var(--seed-color-fg-positive-contrast)",
  warningContrast: "var(--seed-color-fg-warning-contrast)",
};

// Background Colors
export const bg = {
  overlay: "var(--seed-color-bg-overlay)",
  disabled: "var(--seed-color-bg-disabled)",
  brandWeak: "var(--seed-color-bg-brand-weak)",
  brandSolid: "var(--seed-color-bg-brand-solid)",
  brandSolidPressed: "var(--seed-color-bg-brand-solid-pressed)",
  brandWeakPressed: "var(--seed-color-bg-brand-weak-pressed)",
  criticalWeak: "var(--seed-color-bg-critical-weak)",
  criticalSolid: "var(--seed-color-bg-critical-solid)",
  criticalSolidPressed: "var(--seed-color-bg-critical-solid-pressed)",
  criticalWeakPressed: "var(--seed-color-bg-critical-weak-pressed)",
  informativeWeak: "var(--seed-color-bg-informative-weak)",
  informativeSolid: "var(--seed-color-bg-informative-solid)",
  informativeSolidPressed: "var(--seed-color-bg-informative-solid-pressed)",
  informativeWeakPressed: "var(--seed-color-bg-informative-weak-pressed)",
  layerBasement: "var(--seed-color-bg-layer-basement)",
  layerDefault: "var(--seed-color-bg-layer-default)",
  layerFill: "var(--seed-color-bg-layer-fill)",
  layerFloating: "var(--seed-color-bg-layer-floating)",
  layerDefaultPressed: "var(--seed-color-bg-layer-default-pressed)",
  layerFloatingPressed: "var(--seed-color-bg-layer-floating-pressed)",
  magicWeak: "var(--seed-color-bg-magic-weak)",
  neutralWeak: "var(--seed-color-bg-neutral-weak)",
  neutralInverted: "var(--seed-color-bg-neutral-inverted)",
  neutralSolid: "var(--seed-color-bg-neutral-solid)",
  neutralInvertedPressed: "var(--seed-color-bg-neutral-inverted-pressed)",
  neutralSolidMuted: "var(--seed-color-bg-neutral-solid-muted)",
  neutralSolidMutedPressed: "var(--seed-color-bg-neutral-solid-muted-pressed)",
  neutralWeakPressed: "var(--seed-color-bg-neutral-weak-pressed)",
  overlayMuted: "var(--seed-color-bg-overlay-muted)",
  positiveWeak: "var(--seed-color-bg-positive-weak)",
  positiveSolid: "var(--seed-color-bg-positive-solid)",
  positiveSolidPressed: "var(--seed-color-bg-positive-solid-pressed)",
  positiveWeakPressed: "var(--seed-color-bg-positive-weak-pressed)",
  warningWeak: "var(--seed-color-bg-warning-weak)",
  warningSolid: "var(--seed-color-bg-warning-solid)",
  warningSolidPressed: "var(--seed-color-bg-warning-solid-pressed)",
  warningWeakPressed: "var(--seed-color-bg-warning-weak-pressed)",
};

// Stroke Colors
export const stroke = {
  brandWeak: "var(--seed-color-stroke-brand-weak)",
  brandSolid: "var(--seed-color-stroke-brand-solid)",
  criticalWeak: "var(--seed-color-stroke-critical-weak)",
  criticalSolid: "var(--seed-color-stroke-critical-solid)",
  informativeWeak: "var(--seed-color-stroke-informative-weak)",
  informativeSolid: "var(--seed-color-stroke-informative-solid)",
  neutralContrast: "var(--seed-color-stroke-neutral-contrast)",
  neutralSolid: "var(--seed-color-stroke-neutral-solid)",
  neutralWeak: "var(--seed-color-stroke-neutral-weak)",
  neutralMuted: "var(--seed-color-stroke-neutral-muted)",
  neutralSubtle: "var(--seed-color-stroke-neutral-subtle)",
  positiveWeak: "var(--seed-color-stroke-positive-weak)",
  positiveSolid: "var(--seed-color-stroke-positive-solid)",
  warningWeak: "var(--seed-color-stroke-warning-weak)",
  warningSolid: "var(--seed-color-stroke-warning-solid)",
};

// Manner Temp Colors
export const mannerTemp = {
  l1: {
    text: "var(--seed-color-manner-temp-l1-text)",
    bg: "var(--seed-color-manner-temp-l1-bg)",
  },
  l2: {
    text: "var(--seed-color-manner-temp-l2-text)",
    bg: "var(--seed-color-manner-temp-l2-bg)",
  },
  l3: {
    text: "var(--seed-color-manner-temp-l3-text)",
    bg: "var(--seed-color-manner-temp-l3-bg)",
  },
  l4: {
    text: "var(--seed-color-manner-temp-l4-text)",
    bg: "var(--seed-color-manner-temp-l4-bg)",
  },
  l5: {
    text: "var(--seed-color-manner-temp-l5-text)",
    bg: "var(--seed-color-manner-temp-l5-bg)",
  },
  l6: {
    text: "var(--seed-color-manner-temp-l6-text)",
    bg: "var(--seed-color-manner-temp-l6-bg)",
  },
  l7: {
    text: "var(--seed-color-manner-temp-l7-text)",
    bg: "var(--seed-color-manner-temp-l7-bg)",
  },
  l8: {
    text: "var(--seed-color-manner-temp-l8-text)",
    bg: "var(--seed-color-manner-temp-l8-bg)",
  },
  l9: {
    text: "var(--seed-color-manner-temp-l9-text)",
    bg: "var(--seed-color-manner-temp-l9-bg)",
  },
  l10: {
    text: "var(--seed-color-manner-temp-l10-text)",
    bg: "var(--seed-color-manner-temp-l10-bg)",
  },
};
