on:
  pull_request:

name: Check Changeset

jobs:
  check-changeset:
    name: Check Changeset
    runs-on: ubuntu-latest
    if: github.head_ref != 'changeset-release/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            publishable:
              - 'package/**'

      - name: Enable Corepack
        if: steps.changes.outputs.publishable == 'true'
        run: corepack enable

      - uses: actions/setup-node@v4
        if: steps.changes.outputs.publishable == 'true'
        with:
          node-version: 24.x
          cache: 'yarn'

      - run: yarn install --immutable
        if: steps.changes.outputs.publishable == 'true'

      - run: yarn changeset status --since=origin/main
        if: steps.changes.outputs.publishable == 'true'
